# Generated by Django 5.0.3 on 2024-03-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
